name: Back Test Execution
on:
  workflow_call:
    inputs:
      java-version:
        description: "Version of Java"
        required: false
        default: "11"
        type: string
      command-execute:
        description: 'Command to execute the automation project'
        required: true
        type: string
      command-report:
        description: 'Command to generate report'
        required: true
        type: string
      path-report:
        description: 'path of report'
        required: true
        type: string

jobs:
  back-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          architecture: x64
          distribution: "adopt"

      - name: Execute Automated Tests
        if: ${{ inputs.command-execute != '' }}
        run: |
          echo "${{ inputs.command-execute }}"
          eval "${{ inputs.command-execute }}" || exit 1
        continue-on-error: true


      - name: Generate Report
        if: ${{ inputs.command-report != '' }}
        run: |
          echo "${{ inputs.command-report }}"
          eval "${{ inputs.command-report }}" || exit 1

      - name: Artifact-Report
        uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.path-report }}
